version: '2'
services:
  create-fusion-plugin:
    build: .
    environment:
      - CODECOV_TOKEN
      - CI=true
      - BUILDKITE
      - BUILDKITE_BRANCH
      - BUILDKITE_BUILD_NUMBER
      - BUILDKITE_JOB_ID
      - BUILDKITE_BUILD_URL
      - BUILDKITE_PROJECT_SLUG
      - BUILDKITE_COMMIT
  create-fusion-plugin-node-last:
    extends: create-fusion-plugin
    build:
      context: .
      args:
        BASE_IMAGE: 'uber/web-base-image:1.0.9'
